import React from "react";
import "./Report.css";

const COMPLETENESS_LABEL = {
  full: "Screening complete",
  partial: "Partial screening",
  minimal: "Minimal data collected",
};

export default function Report({ report, onRestart }) {
  if (!report) return null;

  const hasRedFlags = report.redFlags && report.redFlags.length > 0;

  return (
    <div className="report">
      <div className="report__sheet">
        <header className="report__header">
          <div>
            <p className="report__eyebrow mono">INTAKE SUMMARY</p>
            <h1 className="report__title">
              {report.patientName ? report.patientName : "Unidentified patient"}
            </h1>
          </div>
          <span className={`report__badge report__badge--${report.completeness || "partial"}`}>
            {COMPLETENESS_LABEL[report.completeness] || "Partial screening"}
          </span>
        </header>

        {report.note && <p className="report__system-note">{report.note}</p>}

        {hasRedFlags && (
          <div className="report__redflag">
            <strong>Flagged for prompt review</strong>
            <ul>
              {report.redFlags.map((f, i) => (
                <li key={i}>{f}</li>
              ))}
            </ul>
          </div>
        )}

        <section className="report__summary">
          <p className="report__label mono">SUMMARY</p>
          <p className="report__summary-text">{report.summary}</p>
        </section>

        <section className="report__grid">
          <Field label="Chief complaint" value={report.chiefComplaint} />
          <Field label="Duration" value={report.duration} />
          <Field label="Severity" value={report.severity} />
          <Field
            label="Associated symptoms"
            value={
              report.associatedSymptoms && report.associatedSymptoms.length
                ? undefined
                : "None reported"
            }
          >
            {report.associatedSymptoms && report.associatedSymptoms.length > 0 && (
              <div className="report__tags">
                {report.associatedSymptoms.map((s, i) => (
                  <span className="report__tag" key={i}>
                    {s}
                  </span>
                ))}
              </div>
            )}
          </Field>
        </section>

        {report.recommendedFollowUp && (
          <section className="report__followup">
            <p className="report__label mono">RECOMMENDED FOLLOW-UP</p>
            <p>{report.recommendedFollowUp}</p>
          </section>
        )}

        <footer className="report__footer">
          <span className="mono">Generated by Aria · not a medical diagnosis</span>
        </footer>
      </div>

      <button className="report__restart" onClick={onRestart}>
        Start a new call
      </button>
    </div>
  );
}

function Field({ label, value, children }) {
  return (
    <div className="report__field">
      <p className="report__label mono">{label.toUpperCase()}</p>
      {children ? children : <p className="report__field-value">{value || "Not mentioned"}</p>}
    </div>
  );
}
